#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/55f56dc3-8961-4a08-92b3-375bac97accf 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  String ouija;
  bool door;
  bool fin;
  bool goodbye;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(115200);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  
}


/*
  Since Door is READ_WRITE variable, onDoorChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onDoorChange()  {
  // Add your code here to act upon Door change
  Serial.print(101);
}

/*
  Since Goodbye is READ_WRITE variable, onGoodbyeChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onGoodbyeChange()  {
  // Add your code here to act upon Goodbye change
    Serial.print(102);
}

/*
  Since Fin is READ_WRITE variable, onFinChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onFinChange()  {
  // Add your code here to act upon Fin change
    Serial.print(103);
}



/*
  Since Ouija is READ_WRITE variable, onOuijaChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onOuijaChange()  {
  // Add your code here to act upon Ouija change
}