// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "ad577af5-b13c-4475-90fa-03893f13ee35";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onOuijaChange();
void onDoorChange();
void onFinChange();
void onGoodbyeChange();

String ouija;
bool door;
bool fin;
bool goodbye;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(ouija, READWRITE, ON_CHANGE, onOuijaChange);
  ArduinoCloud.addProperty(door, READWRITE, ON_CHANGE, onDoorChange);
  ArduinoCloud.addProperty(fin, READWRITE, ON_CHANGE, onFinChange);
  ArduinoCloud.addProperty(goodbye, READWRITE, ON_CHANGE, onGoodbyeChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
